// src/components/MarkEditDialog/chinaPortsData.js
// 精简版示例，实际可接入完整港口数据库或API

export const CHINA_PORTS = [
    { code: 'CNHKG', name: '香港港', py: 'xianggang' },
    { code: 'CNSHA', name: '上海港', py: 'shanghai' },
    { code: 'CNNGB', name: '宁波舟山港', py: 'ningbo' },
    { code: 'CNSZX', name: '深圳港', py: 'shenzhen' },
    { code: 'CNQIN', name: '青岛港', py: 'qingdao' },
    { code: 'CNTAO', name: '天津港', py: 'tianjin' },
    { code: 'CNDLC', name: '大连港', py: 'dalian' },
    { code: 'CNXMN', name: '厦门港', py: 'xiamen' },
    { code: 'CNGZH', name: '广州港', py: 'guangzhou' },
    { code: 'CNZHA', name: '湛江港', py: 'zhanjiang' },
    { code: 'CNLYG', name: '连云港港', py: 'lianyungang' },
    { code: 'CNYTN', name: '烟台港', py: 'yantai' },
    { code: 'CNWEI', name: '威海港', py: 'weihai' },
    { code: 'CNFUG', name: '福州港', py: 'fuzhou' },
    { code: 'CNQUZ', name: '泉州港', py: 'quanzhou' },
    { code: 'CNZOS', name: '舟山港', py: 'zhoushan' },
    { code: 'CNJZH', name: '锦州港', py: 'jinzhou' },
    { code: 'CNRYZ', name: '日照港', py: 'rizhao' },
    { code: 'CNHLD', name: '葫芦岛港', py: 'huludao' },
    { code: 'CNYNK', name: '营口港', py: 'yingkou' },
    { code: 'CNDNG', name: '丹东港', py: 'dandong' },
    { code: 'CNHUA', name: '黄骅港', py: 'huanghua' },
    { code: 'CNLONG', name: '龙口港', py: 'longkou' },
    { code: 'CNWEF', name: '潍坊港', py: 'weifang' },
    { code: 'CNLAN', name: '岚山港', py: 'lanshan' },
    { code: 'CNDSN', name: '董家口港', py: 'dongjiakou' },
    { code: 'CNLIY', name: '连云港', py: 'lianyungang' },
    { code: 'CNYCH', name: '盐城港', py: 'yancheng' },
    { code: 'CNNTG', name: '南通港', py: 'nantong' },
    { code: 'CNZJI', name: '张家港', py: 'zhangjiagang' },
    { code: 'CNJIA', name: '江阴港', py: 'jiangyin' },
    { code: 'CNTAG', name: '太仓港', py: 'taicang' },
    { code: 'CNHAI', name: '海门港', py: 'haimen' },
    { code: 'CNWEN', name: '温州港', py: 'wenzhou' },
    { code: 'CNTAO2', name: '台州港', py: 'taizhou' },
    { code: 'CNJIO', name: '嘉兴港', py: 'jiaxing' },
    { code: 'CNHAI2', name: '海口港', py: 'haikou' },
    { code: 'CNSAN', name: '三亚港', py: 'sanya' },
    { code: 'CNBAS', name: '八所港', py: 'basuo' },
    { code: 'CNMAW', name: '茂名港', py: 'maoming' },
    { code: 'CNZHU', name: '珠海港', py: 'zhuhai' },
    { code: 'CNJIA2', name: '江门港', py: 'jiangmen' },
    { code: 'CNZHO', name: '中山港', py: 'zhongshan' },
    { code: 'CNFOS', name: '佛山港', py: 'foshan' },
    { code: 'CNQIN2', name: '钦州港', py: 'qinzhou' },
    { code: 'CNBEI', name: '北海港', py: 'beihai' },
    { code: 'CNFAN', name: '防城港', py: 'fangchenggang' },
    { code: 'CNHAI3', name: '海口新海港', py: 'haikouxin' },
    { code: 'CNHAI4', name: '海安港', py: 'haian' },
    { code: 'CNXIN', name: '新会港', py: 'xinhui' }
  ]
  